# Generated by Django 2.2.5 on 2020-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_bord',
            name='Notice_name',
            field=models.CharField(max_length=200),
        ),
    ]
