# Generated by Django 2.2.5 on 2020-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livtv',
            name='iframe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class_note',
            name='note_img',
            field=models.ImageField(default='note_img_s/tgtgvt.jpg', upload_to='note_img_s/'),
        ),
    ]
