# Generated by Django 2.2.5 on 2020-06-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('live_tv_url', models.URLField(max_length=500)),
            ],
        ),
    ]
