# Generated by Django 2.2.5 on 2020-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_note',
            name='note_img',
            field=models.ImageField(upload_to='note_img_s/'),
        ),
    ]
