# Generated by Django 2.2.5 on 2020-06-17 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0002_class_note_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_bord',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
