# Generated by Django 2.2.5 on 2020-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0002_auto_20200617_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_bord',
            name='document_notice',
            field=models.FileField(default=1, upload_to='documents_notice_bord/'),
            preserve_default=False,
        ),
    ]
