# Generated by Django 2.2.5 on 2020-06-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0002_apps_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps_about',
            old_name='title',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='apps_about',
            old_name='live_tv_url',
            new_name='facebook_link',
        ),
    ]
