# Generated by Django 2.2.5 on 2020-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0003_auto_20200705_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livtv',
            name='iframe',
            field=models.CharField(default='0', max_length=800),
        ),
    ]
