# Generated by Django 2.2.5 on 2020-06-17 10:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0003_auto_20200617_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_bord',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
