# Generated by Django 2.2.5 on 2020-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0003_notice_bord_document_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_info',
            name='img',
            field=models.ImageField(default='Academic_Info/tgtgvt.jpg', upload_to='Academic_Info/'),
        ),
    ]
