# Generated by Django 2.2.5 on 2020-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0004_auto_20200617_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_note',
            name='slug',
        ),
        migrations.AlterField(
            model_name='class_note',
            name='note_img',
            field=models.ImageField(default='note_img_s//tgtgvt.jpg', upload_to='note_img_s/'),
        ),
        migrations.AlterField(
            model_name='notice_bord',
            name='img',
            field=models.ImageField(default='notice_img_bord/fvfv.jpg', upload_to='notice_img_bord/'),
        ),
    ]
