# Generated by Django 2.2.5 on 2020-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0005_auto_20200617_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_note',
            name='document',
            field=models.FileField(default='no img', upload_to='documents/'),
        ),
    ]
