# Generated by Django 2.2.5 on 2020-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0006_auto_20200617_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_bord',
            name='document_notice',
            field=models.FileField(default='no pdf file', upload_to='documents_notice_bord/'),
        ),
    ]
