# Generated by Django 2.2.5 on 2020-06-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voutv', '0007_auto_20200617_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_note',
            old_name='document',
            new_name='Pdf_file',
        ),
        migrations.RenameField(
            model_name='notice_bord',
            old_name='document_notice',
            new_name='Pdf_file',
        ),
    ]
